package com.rtpa.examples.org;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "PERSON_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(name = "PERSON_ID_GENERATOR", sequenceName = "PERSON_ID_SEQ")
   private java.lang.String name;

   private java.lang.Integer age;

   private java.lang.Boolean adult;

   public Person()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.Boolean getAdult()
   {
      return this.adult;
   }

   public void setAdult(java.lang.Boolean adult)
   {
      this.adult = adult;
   }

   public Person(java.lang.String name, java.lang.Integer age,
         java.lang.Boolean adult)
   {
      this.name = name;
      this.age = age;
      this.adult = adult;
   }

}